app/server/models.py
# project/server/models.py


import datetime
from flask import current_app
from app.server import db, bcrypt


# class PreReleaseFormObj(db.Model):
#     __tablename__ = "pre_release_form"
#
#     id = db.Column(db.Integer, primary_key=True, autoincrement=True)
#     name = db.Column(db.String(255))
#     email = db.Column(db.String(255))
#     type = db.Column(db.String(255))
#     signedup_on = db.Column(db.DateTime)
#
#
#     def __init__(self, email, name, type):
#         self.email = email
#         self.name = name
#         self.type = type
#         self.signedup_on = datetime.datetime.now()
#
# #     def __repr__(self):
#         return '<User {0}>'.format(self.email)

class User(db.Document):
    username = db.StringField(unique=True, required = True)
    email = db.EmailField(unique=True, required=True)
    password = db.StringField(required=True)
    admin = db.BooleanField(default=False)
    active = db.BooleanField(default=True)
    registered_on = db.DateTimeField(default=datetime.datetime.now())



    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def __repr__(self):
        return '<User {0}>'.format(self.email)

app/server/user/forms.py
# project/server/user/forms.py


from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo


class LoginForm(FlaskForm):
    username = StringField('Username', [DataRequired()])
    password = PasswordField('Password', [DataRequired()])


class RegisterForm(FlaskForm):
    username = StringField(
        'Username',
        validators=[
            DataRequired(),
            Length(min=1, max=40)
        ]
    )

    email = StringField(
        'Email Address',
        validators=[
            DataRequired(),
            Email(message=None),
            Length(min=6, max=40)
        ]
    )
    password = PasswordField(
        'Password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Confirm password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

app/server/__init__.py
import os

from flask import Flask, render_template
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_debugtoolbar import DebugToolbarExtension
from flask_bootstrap import Bootstrap
from flask_mongoengine import MongoEngine, MongoEngineSessionInterface
from flask_migrate import Migrate


# instantiate the extensions
login_manager = LoginManager()
bcrypt = Bcrypt()
toolbar = DebugToolbarExtension()
bootstrap = Bootstrap()
db = MongoEngine()
migrate = Migrate()


def create_app():

    # instantiate the app
    app = Flask(
        __name__,
        template_folder='../client/templates',
        static_folder='../client/static'
    )

    # set config
    app_settings = os.getenv(
        'APP_SETTINGS', 'app.server.config.DevelopmentConfig')
    app.config.from_object(app_settings)

    # set up extensions
    login_manager.init_app(app)
    bcrypt.init_app(app)
    toolbar.init_app(app)
    bootstrap.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    app.session_interface = MongoEngineSessionInterface(db)

    # register blueprints
    from app.server.user.views import user_blueprint
    app.register_blueprint(user_blueprint)
    from app.server.account.views import account_blueprint
    app.register_blueprint(account_blueprint)

    # flask login
    from app.server.models import User
    login_manager.login_view = 'user.login'
    login_manager.login_message_category = 'danger'

    @login_manager.user_loader
    def load_user(id):
        user = models.User.objects.with_id(id)
        return user


    # error handlers
    # @app.errorhandler(401)
    # def unauthorized_page(error):
    #     return render_template('errors/401.html'), 401
    #
    # @app.errorhandler(403)
    # def forbidden_page(error):
    #     return render_template('errors/403.html'), 403
    #
    # @app.errorhandler(404)
    # def page_not_found(error):
    #     return render_template('errors/404.html'), 404
    #
    # @app.errorhandler(500)
    # def server_error_page(error):
    #     return render_template('errors/500.html'), 500

    return app

app/server/account/views.py
# project/server/main/views.py

import os
from flask import render_template, Blueprint, request, flash, redirect, url_for, current_app
from app.server.user.forms import LoginForm, RegisterForm
from flask_login import login_user, logout_user, login_required
from app.server import db, models, bcrypt
import flask_whooshalchemy

basedir = os.path.abspath(os.path.dirname(__file__))
account_blueprint = Blueprint('account', __name__,)

@login_required
@account_blueprint.route("/<username>", methods=['GET', 'POST'])
def main(username):
    return render_template('account/account.html', username = username)

app/server/user/views.py
# project/server/main/views.py

import os
from flask import render_template, Blueprint, request, flash, redirect, url_for, current_app
from app.server.user.forms import LoginForm, RegisterForm
from flask_login import login_user, logout_user, login_required
from app.server import db, models, bcrypt
import flask_whooshalchemy

basedir = os.path.abspath(os.path.dirname(__file__))
user_blueprint = Blueprint('user', __name__,)

@user_blueprint.route("/", methods=['GET', 'POST'])
def main():
    return render_template('user/main.html')

@user_blueprint.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        try:
            user = models.User.objects.get(username=form.username.data)
        except:
            user = None
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('user.main'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', form = form)

@user_blueprint.route("/register", methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = models.User(
            username = form.username.data,
            email=form.email.data,
            password=bcrypt.generate_password_hash(form.password.data,
                current_app.config.get('BCRYPT_LOG_ROUNDS')).decode('utf-8'),
            admin = False
        )

        user.save()

        login_user(user)
        flash('You are logged in. Welcome to Gallery!', 'success')
        return redirect(url_for('user.main'))

    return render_template('user/register.html', form = form)



@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'success')
    return redirect(url_for('user.main'))

app/client/templates/_base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Gallery is a platform that brings digital art into reality.">
    <meta name="author" content="Saahith Pochiraju, Duncan Cock Foster">
    <meta name="keywords" content="Gallery, Blockchain, Digital Art ">
    <title> Gallery </title>
    <link rel="icon" href="{{url_for('static', filename='images/art.png')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/style.css')}}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" >
    {% block css %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110682568-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-110682568-2');
    </script>

</head>




<body id="hero">
    {% include 'header.html' %}

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <br>
              <div class="row">
                <div class="col-md-12 flash">
                  {% for category, message in messages %}
                  <div class="alert alert-{{ category }} modern">
                    <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
                   {{message}}
                  </div>
                  {% endfor %}
                </div>
              </div>
          </br>
      {% endif %}
    {% endwith %}

    <!-- child template -->
    {% block content %}{% endblock %}

    {% include 'footer.html' %}

<!-- scripts -->
    <script src="{{url_for('static', filename='js/particles.js')}}" type="text/javascript"></script>

    <script>
    var particleContainer = document.querySelector('#hero')
        var particleOptions = {
          density: 10000,
          velocity: 0.5
        }

        new ParticleNetwork(particleContainer, particleOptions)
    </script>
    {% block js %}{% endblock %}

</body>

</html>

app/client/templates/footer.html
<footer class="container-fluid">
    <div class = "row">
        <div class = "col">
            <nav class="bottombar">
                <ul>
                    <li><a href="https://www.instagram.com/visitgallery/"><img class="resize1" src="{{url_for('static', filename='images/ig.png')}}"/></a></li>
                    <li><a href="https://twitter.com/visitgallery?s=07"><img class="resize1" src="{{url_for('static', filename='images/twitter.png')}}"/></a></li>
                </ul>
            </nav>
        </div>
    </div>
</footer>

app/client/templates/header.html
<header style="width:100%;background-color:black;position:fixed;z-index:50">
  <nav class="navbar navbar-expand-lg" >
    <div class="navbar-header"><a class="modern" style="text-decoration:none;color:white" href="/">Gallery</a></div>
    <ul class="nav navbar-nav ml-auto">
      {% if current_user.is_authenticated %}
        <li class="nav-item nav-link"><a class="modern link-1" href="{{ url_for('account.main') }}">{{current_user.username}}</a></li>
      {% else %}
        <li class="nav-item nav-link"><a class="modern link-1" href="{{url_for('user.login') }}">Log In</a></li>
        <li class="nav-item nav-link"><a class="modern link-1" href="{{url_for('user.register') }}">Register</a></li>
      {% endif %}
      {% if current_user.is_authenticated %}
        <li class="nav-item nav-link"><a class="modern link-1" href="{{ url_for('user.logout') }}">Logout</a></li>
      {% endif %}
    </ul>
  </nav>
</header>

app/client/templates/user/login.html
{% extends '_base.html' %}

{% block content %}

<form class="forms" role="form" method="POST" action="/login">
    {{ form.csrf_token }}
    <h2 class = "modern"> Log In </h2>
    <div class="form-group">
        {{ form.username(class="form-control modern", placeholder="username")}}
    </div>
    <div class="form-group">
        {{ form.password(class="form-control modern" , placeholder="password", type="password")}}
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-light" style="font-family:GeosansLight">Submit</button>
    </div>
</form>


{% endblock content %}

app/client/templates/user/main.html
{% extends '_base.html' %}

{% block content %}




{% endblock content %}

app/client/templates/user/register.html
{% extends '_base.html' %}

{% block content %}

<form class="forms" role="form" method="POST" action="/register">
    {{ form.csrf_token }}
    {{ form.hidden_tag()}}
    <h2 class = "modern"> Register </h2>
    <div class="form-group">
        {{ form.username(class="form-control modern", placeholder="username")}}
    </div>
    <div class="form-group">
        {{ form.email(class="form-control modern", placeholder="email", type='email')}}
    </div>
    <div class="form-group">
        {{ form.password(class="form-control modern" , placeholder="password", type="password")}}
    </div>
    <div class="form-group">
        {{ form.confirm(class="form-control modern" , placeholder="confirm password", type="password")}}
    </div>
    <div class="form-group">
        <button type="button submit" class="btn btn-light" style="font-family:GeosansLight">Submit</button>
    </div>
</form>


{% endblock content %}